all: postgres pgloader ;

postgres:
	#git clone --filter=tree:0 https://git.postgresql.org/git/postgresql.git
	git clone --bare --filter=tree:0 https://github.com/postgres/postgres.git

pgloader:
	git clone --filter=tree:0 https://github.com/dimitri/pgloader.git
