#!/usr/bin/env python3
"""
Generate data/natural_earth/ne_50m_countries.sql from Natural Earth GeoJSON.

Downloads ne_50m_admin_0_countries.geojson from the nvkelso/natural-earth-vector
GitHub repo and emits INSERT statements using ST_GeomFromGeoJSON().

Usage:
    python3 tooling/gen-ne-50m-sql.py

Output:
    data/natural_earth/ne_50m_countries.sql  (~3.4 MB, committed to git)
"""

import json
import sys
import urllib.request
from pathlib import Path

URL = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
    "master/geojson/ne_50m_admin_0_countries.geojson"
)

OUT = Path(__file__).parent.parent / "data" / "natural_earth" / "ne_50m_countries.sql"


def fetch_geojson(url: str) -> dict:
    print(f"Downloading {url} ...", file=sys.stderr)
    with urllib.request.urlopen(url, timeout=120) as r:
        data = json.load(r)
    print(f"  {len(data['features'])} features loaded", file=sys.stderr)
    return data


def escape(s: str) -> str:
    return s.replace("'", "''") if s else ""


def feature_to_insert(feat: dict) -> str:
    props = feat.get("properties") or {}
    name = escape(str(props.get("NAME") or props.get("name") or "Unknown"))
    iso2 = props.get("ISO_A2") or props.get("iso_a2") or ""
    if iso2 == "-99":
        iso2 = ""
    iso2_sql = f"'{escape(iso2)}'" if iso2 else "NULL"

    geom_json = json.dumps(feat["geometry"], separators=(",", ":"))
    # Escape single quotes in JSON (extremely rare but possible)
    geom_json = geom_json.replace("'", "''")

    return (
        f"INSERT INTO natural_earth.ne_countries (name, iso_a2, geom) VALUES\n"
        f"('{name}', {iso2_sql}, ST_GeomFromGeoJSON('{geom_json}'));"
    )


def main():
    data = fetch_geojson(URL)
    features = data["features"]

    lines = [
        "-- Natural Earth 50m countries — INSERT data",
        "-- Generated by tooling/gen-ne-50m-sql.py — do not edit by hand.",
        f"-- Source: {URL}",
        f"-- Features: {len(features)}",
        "",
    ]

    for feat in features:
        lines.append(feature_to_insert(feat))

    sql = "\n".join(lines) + "\n"
    OUT.write_text(sql, encoding="utf-8")
    size_kb = OUT.stat().st_size / 1024
    print(f"Wrote {OUT}  ({size_kb:.0f} KB, {len(features)} rows)", file=sys.stderr)


if __name__ == "__main__":
    main()
